---
    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: yes

    - name: remove dependencies that are no longer required
      become: yes
      apt:
        autoremove: yes

    - name: "install nodejs"
      become: yes
      apt:
        name: ["nodejs", "npm"]
        state: latest
        update_cache: yes

    - name: "install python3"
      become: yes
      npm:
        name: python3
        global: yes
        production: yes
        state: present

    - name: "install pm2"
      become: yes
      npm:
        name: pm2
        global: yes
        production: yes
        state: present

    - name: "install nodejs"
      become: yes
      apt:
        name: ["nodejs", "npm"]
        state: latest
        update_cache: yes

    - name: "copy backend build to ec2-instance"
      copy:
        src: /tmp/backend.tar.gz
        dest: /tmp/backend.tar.gz
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Extract backend.tar.gz
      unarchive:
        src: /tmp/backend.tar.gz
        dest: /home/ubuntu/backend

    - name:  Install npm deps
      shell: npm i
      failed_when: '"ERR!" in npm_finished.stderr'
      args:
        chdir: /home/ubuntu/backend