---
    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: yes

    - name: remove dependencies that are no longer required
      become: yes
      apt:
        autoremove: yes

    - name: "install nodejs"
      become: yes
      apt:
        name: ["nodejs", "npm"]
        state: latest
        update_cache: yes

    - name: "install python3"
      become: yes
      npm:
        name: python3
        global: yes
        production: yes
        state: present

    - name: "install pm2"
      become: yes
      npm:
        name: pm2
        global: yes
        production: yes
        state: present

    - name: "install nodejs"
      become: yes
      apt:
        name: ["nodejs", "npm"]
        state: latest
        update_cache: yes

    - name: Create backend directory
      file:
        path: /home/ubuntu/backend
        state: directory
        mode: '0755'

    - name: Set dotenv
      shell: |
        echo NODE_ENV=production > .env
        echo VERSION=1 >> .env
        echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION >> .env
        echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR >> .env
        echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES >> .env
        echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS >> .env
        echo TYPEORM_HOST=$TYPEORM_HOST >> .env
        echo TYPEORM_PORT=$TYPEORM_PORT >> .env
        echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> .env
        echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> .env
        echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> .env
      args:
        chdir: /home/ubuntu/backend

#    - name: Start pm2
#      command: pm2 start npm --no-automation --name udapeople_backend -- run start
#      args:
#        chdir: /home/ubuntu/backend

