---
    - name: "copy backend build to ec2-instance"
      copy:
        src: /tmp/backend.tar.gz
        dest: /tmp/backend.tar.gz
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Extract backend.tar.gz
      unarchive:
        src: /tmp/backend.tar.gz
        dest: /home/ubuntu/

    - name: Start pm2
      command: pm2 start npm --no-automation --name udapeople_backend -- run start
      args:
        chdir: /home/ubuntu/dist
