---
    - name: "copy backend build to ec2-instance"
      copy:
        src: /home/circleci/project/backend/dist
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Start pm2
      command: pm2 start npm --no-automation --name udapeople_backend -- run start
      args:
        chdir: /home/ubuntu/dist
